### ISSUE TITLE
A question for Running "poetry run plasma_store -m 2000000000 -s /tmp/plasma"

### ISSUE THREAD

**Issue by RyanZhang307** [mila-iqia/Casande-RL#1]
Hello, after I run the code "poetry install" and the code "poetry run plasma_store -m 2000000000 -s /tmp/plasma", I got the following error messages:

/arrow/cpp/src/plasma/store.cc:1274: Allowing the Plasma store to use up to 2GB of memory.
/arrow/cpp/src/plasma/store.cc:1297: Starting object store with directory /dev/shm and huge page support disabled
/arrow/cpp/src/plasma/store.cc:754: Disconnecting client on fd 7
/arrow/cpp/src/plasma/store.cc:754: Disconnecting client on fd 6
/arrow/cpp/src/plasma/store.cc:754: Disconnecting client on fd 7
/arrow/cpp/src/plasma/store.cc:754: Disconnecting client on fd 6

I don't know how to solve it, can you help me?

**Comment by afansi** [comment]
> Hello, after I run the code "poetry install" and the code "poetry run plasma_store -m 2000000000 -s /tmp/plasma", I got the following error messages:
> 
> /arrow/cpp/src/plasma/store.cc:1274: Allowing the Plasma store to use up to 2GB of memory. /arrow/cpp/src/plasma/store.cc:1297: Starting object store with directory /dev/shm and huge page support disabled /arrow/cpp/src/plasma/store.cc:754: Disconnecting client on fd 7 /arrow/cpp/src/plasma/store.cc:754: Disconnecting client on fd 6 /arrow/cpp/src/plasma/store.cc:754: Disconnecting client on fd 7 /arrow/cpp/src/plasma/store.cc:754: Disconnecting client on fd 6
> 
> I don't know how to solve it, can you help me?

These are not error messages. These are notifications that a client app disconnects itself from the store.
